# Generated by Django 4.2.4 on 2023-09-03 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likemessage',
            field=models.ManyToManyField(blank=True, related_name='likemessage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='likeroom',
            field=models.ManyToManyField(blank=True, related_name='likeroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
